import com.drools.DroolsTest.Message;

rule "Hello World"
ruleflow-group "g1"
    no-loop true
    lock-on-active true
    salience 2
    when
        m : Message( when(), status == Message.HELLO, myMessage : message )
        //ConditionFactory(when(m, "xx.xxx.xxx.xx"))
    then
        //RuleFactory(then(m, "xxx.xx.xxx"));
        m.println();
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        //update( m );
end

rule "GoodBye"
ruleflow-group "g2"
    no-loop true
    lock-on-active true
    salience 1
    when
        m: Message(when(), status == Message.GOODBYE)
    then
        m.setStatus(0);
        m.println();
       // update( m );
end

rule "zhu zhu"
ruleflow-group "g3"
    no-loop true
    lock-on-active true
    salience 0
    when
        eval(true)
        m: Message(when() , status == 0)
    then
        m.setMessage( "zhuzhu" );
        m.println();
end

